data:
  train_bs: 1
  train_width: 320
  train_height: 512
  meta_paths:
    - "/home/ReferenceSVD/assets/data/meta/单人8011_成年_女性_非绿幕_转身_02_010.json"

  # Margin of frame indexes between ref and tgt images
  sample_rate: 10 
  n_sample_frames: 14
  num_workers: 8
  fps: 7
  motion_bucket_id: 40

noise_scheduler:
  P_mean: 0.7
  P_std: 1.6
  sigma_data: 1

val_data:
  infer_width: 320 
  infer_height: 512
  decode_chunk_size: 8
  motion_bucket_id: 40
  fps: 7
  noise_aug_strength: 0.02
  num_inference_steps: 25
  min_guidance_scale: 1.0
  max_guidance_scale: 3.0
  tile_size: 16 
  tile_overlap: 2
  ref_images: 
    - "/home/ReferenceSVD/assets/test/4.png"
    - "/home/ReferenceSVD/assets/test/2.png"
  drive_poses:
    - "/home/ReferenceSVD/assets/data/dwpose_video/extracted_单人8011_成年_女性_非绿幕_转身_02_010_tracking_demo_masked.mp4"
    - "/home/ReferenceSVD/assets/data/dwpose_video/extracted_单人8011_成年_女性_非绿幕_转身_02_010_tracking_demo_masked.mp4"
  background_images:
    - "/home/ReferenceSVD/assets/test/3.png"
    - "/home/ReferenceSVD/assets/test/back1.jpg"

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: True
  gradient_checkpointing: True 
  max_train_steps: 100000
  
  max_grad_norm: 1.0
  # lr
  learning_rate: 1.0e-4
  scale_lr: False 
  lr_warmup_steps: 500
  lr_scheduler: 'constant'[]

  # optimizer
  use_8bit_adam: False
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

allow_tf32: True
total_limit: 20
save_model_epoch_interval: 20
use_ema: False
random_null_ratio: 0.05
target_ema_decay: 0.95
checkpointing_steps: 500
pretrained_model_name_or_path: "/home/ReferenceSVD/assets/models/SVD-xt-1-1"
pretrained_sd_model_name_or_path: "/home/ReferenceSVD/assets/models/stable-diffusion-2-1"

reference_net_checkpoint_path: ""
unet_checkpoint_path: ""
pose_guider_checkpoint_path: ""

# reference_net_checkpoint_path: "exp_outputs/reference_net_xt-1-1_16frames_640x960_bs2_szr/model_reference_net-18000.pth"
# unet_checkpoint_path: "exp_outputs/reference_net_xt-1-1_16frames_640x960_bs2_szr/model_unet-18000.pth"
# pose_guider_checkpoint_path: "exp_outputs/reference_net_xt-1-1_16frames_640x960_bs2_szr/model_pose_guider-18000.pth"
pretrained_text_path: ""
resume_from_checkpoint: False
pose_guider_pretrain: False

seed: 1234
exp_name: 'reference_net_xt-1-1_16frames_640x960_bs2_szr_continue'
output_dir: 'exp_outputs'  
